spring:
    datasource:
        url: jdbc:mysql://localhost:3306/l?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
    jpa:
        show-sql: true
        generate-ddl: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: mysql
    profiles:
        active: dev
    mail:
        username: pt_liangyue@outlook.com
        password: 123456789
        host: smtp.exmail.qq.com
        properties:
            mail.smtp.ssl.auth: true
            mail.smtp.ssl.enable: true
            mail.smtp.ssl.required: true
        port: 25
server:
    port: 8931

erupt-app:
    # 登录几次出现验证码，值为0时表示一直需要登录验证码（1.6.1版本开始支持）
    verifyCodeCount: 2
erupt:
    # 是否开启csrf防御
    csrfInspect: true
    # 开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置
    redisSession: false
    # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
    uploadPath: ~/pictures2
    # 是否保留上传文件原始名称
    keepUploadFileName: false
    # 登录session时长（redisSession为true时有效）
    upms.expireTimeByLogin: 60
    # 是否开启任务调度（导入erupt-job时有效）
    job.enable: true
    # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
    security.recordOperateLog: true